### PR TITLE
Update openssl to 1.1.1w and 3.1.6.

### PR DESCRIPTION
**Pull request by carlonluca**

### CODE REVIEW

**Review by Issam-b — CHANGES_REQUESTED** [review]
Could you also update the versions in the build script https://github.com/KDAB/android_openssl/blob/master/build_ssl.sh#L20C12-L20C28?

Is this build using the script from https://github.com/KDAB/android_openssl/pull/61?

**Comment by carlonluca** [comment]
Updated the script.
Yes, this is built using the updated script.

**Comment by omergoktas** [comment]
@Issam-b @bog-dan-ro, are you seriously going to accept pull requests containing binary blobs? Boss move if so, just sayin'. I hope these kind of moves don't not create another Jia Tan incident. I trust @KDAB because I know the people who work there; but I don't know these people (people in pull requests). Why would I integrate binary blobs produced by strangers?

**Comment by Issam-b** [comment]
@omergoktas you bring a valid point indeed! Instead, @bog-dan-ro or I would do the update separately and this can be closed.

**Comment by omergoktas** [comment]
Thank you, @Issam-b. And I didn't mean to be rude to @carlonluca or anyone trying to contribute to the project, either. You know, that's just how you ensure the security of your repo. Code contributions are ok, but binary is somewhat problematic. Again, thanks to all sides who have been trying to be helpful. 🙏

**Comment by carlonluca** [comment]
It seems more than reasonable to me. Thanks.

**Pull request closed without merging**
