### PR TITLE
Let pri file handle dependency resolution according to the Qt version

### PR DESCRIPTION
**Pull request by Issam-b**
Re-organize the libs structure such that, the right libs will be included
depending on the Qt version being used, to make users' life easier.
This practically combines previous tags/branches into master.

### CODE REVIEW

**Comment by bog-dan-ro** [comment]
Thanks Assam!
The only problem I see is that the `build_ssl.sh` scrip which should download and compile both ssl versions in one go.

**Comment by Issam-b** [comment]
> Thanks Assam!
> The only problem I see is that the `build_ssl.sh` scrip which should download and compile both ssl versions in one go.

I'll try to combine that one as well.

**Comment by bog-dan-ro** [comment]
Try to see if using the latest NDK works (theoretically it should but only theoretically)

**Comment by Issam-b** [comment]
This should be fine, now :)

**Comment by bog-dan-ro** [comment]
I'm on it

**Comment by bog-dan-ro** [comment]
Merged it manually

**Pull request closed without merging**
