### PR TITLE
Fix the Qt 5.12.3 case

### PR DESCRIPTION
**Pull request by rferrazz**
Qt 5.12.3 was not falling on the right case

### CODE REVIEW

**Comment by bog-dan-ro** [comment]
@Issam-b ^ ?

**Review by israelins85 — APPROVED** [review]
looks like ok

**Comment by rferrazz** [comment]
@israelins85 so can this be merged?

**Comment by israelins85** [comment]
Yes I used this patch, and its ok.

**Comment by Issam-b** [comment]
@bog-dan-ro this fix is valid, @rferrazz thanks for the fix :)

**Pull request merged**
