### PR TITLE
Quite a few changes

### PR DESCRIPTION
**Pull request by bog-dan-ro**
- Nuke the support for super old Qt versions
 - Simplify a lot openssl.pri and CMakeLists.txt
 - Use latest OpenSSL 1.1.1 version
 - Add OpenSSL 3.x support needed for Qt 6.5

Close: #25, #36, #37, #39

### CODE REVIEW

**Comment by bog-dan-ro** [comment]
> All seems good for me. I tested on my app and build is fine for all ABI and startup test in successful (I tested only on arm64-v8a).

Did you tested cmake or qmake projects? I'm asking because right now I'm testing the qmake ones.

@Issam-b if you have time please review this patch. Thanks.

**Comment by ApiTracer** [comment]
I tested only the cmake way

**Comment by bog-dan-ro** [comment]
> I tested only the cmake way

Great, thanks a lot !

**Comment by triplef** [comment]
Thanks for the updates! Would be great if the specific OpenSSL versions used could be documented e.g. in the README.

**Pull request merged**
