### PR TITLE
Build and use openssl with no-asm for Qt debug buils

### LINKED ISSUE #10: Crash when try to debug app
Try to debug app while this libraries are included causes a crash. See image
debugger_crash

Qt Creator 4.11.1 and an earlier maybe 4.10.x
Qt 5.12.6 and 5.12.7
Android 9, but also in Android 7.1
Kubuntu 19.10

Workaround : Temporary commenting the entry in *.pro file

### PR DESCRIPTION
**Pull request by bog-dan-ro**
Fixes #10, #14

### CODE REVIEW

**Comment by bog-dan-ro** [comment]
@Issam-b please check if the Cmake changes still works.
@sagiadinos @mbruel The patch should fix the crash in debug mode, it ill be great if you'll have time to confirm that it works.

**Comment by mbruel** [comment]
Hi Bogdan,
I've tested your debug_crash_fix branch and it's working well in debug mode on my device.

`D libSmsPolling_arm64-v8a.so: "SSL support: yes, build version: OpenSSL 1.1.1d  10 Sep 2019, system version: OpenSSL 1.1.1f  31 Mar 2020"`

One remark: you should clean the git repo history. 236M is too much and it will increase with the time. I don't see the benefit to keep previous releases 1.1.d...
I recommand you [BFG repo cleaner](https://rtyley.github.io/bfg-repo-cleaner/) which is much faster and easier than git filter-branch (talking about few sec instead of few minutes).

**Comment by bog-dan-ro** [comment]
@mbruel I can't reset the HEAD of this branch, there are people that are still using the old versions.
You can use  `$ git clone` with `--depth=1` to get only the latest version.

**Comment by mbruel** [comment]
ok thx, I didn't know this `--depth=1`

**Comment by sagiadinos** [comment]
Hi Bogdan,

unfortunately the debug crash still exists. Same error as in issue #10.

Qt Creator 4.11.2, Qt 5.12.7
Android 7.1 armv7
Kubuntu 19.10

As this repository is used as sub module I merged with
git submodule update --remote --merge
I also verified with a hex editor, that this is the latest correct version 1.1.1f

**Comment by bog-dan-ro** [comment]
@sagiadinos can you please double check if you have the `no-asm` folder ? also paste here first 10 lines from `openssl.pri` file.

**Comment by sagiadinos** [comment]
@bog-dan-ro 
I indeed overlooked the different branches. Now it debugs as expected.
Thank you!

**Comment by Issam-b** [comment]
@bog-dan-ro Works fine with CMake as well, as usual on OnePlus 7, Galaxy S9, Pixel C.

**Pull request merged**
